name: Deploy App
on: push

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: /home/www/mine-sweeper

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Install and Build # 安装依赖
        run: |
          pnpm install
          pnpm build
      - name: Ensure folder and clean it except node_modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            mkdir -p ${{ env.DEPLOY_PATH }}
            cd ${{ env.DEPLOY_PATH }}
            find -delete
          # find ! -path "./node_modules" ! -path "./node_modules/*" ! -path "./yarn.lock" ! -path "./.env" -delete

      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          source: "./dist/*" # Local file path - REQUIRED false - DEFAULT ./
          strip_components: 1 # 复制后，移除目录层数（docs/.vuepress/dist/* => [target]/*）
          target: ${{ env.DEPLOY_PATH }} # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}} # Remote server address - REQUIRED true
          port: ${{secrets.PORT}} # Remote server port - REQUIRED false - DEFAULT 22
          username: ${{secrets.USERNAME}} # Remote server user - REQUIRED true
          password: ${{secrets.PASSWORD}} # User password - REQUIRED at least one of "password" or "key"


      # - name: Run app with pm2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script_stop: true
      #     script: |
      #       export NVM_DIR=~/.nvm
      #       source ~/.nvm/nvm.sh
      #       cd ${{ env.DEPLOY_PATH }}
      #       yarn
      #       yarn build
      #       pm2 start pm2.config.yml
